# This is a basic workflow to help you get started with Actions

name: test

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"

  buildAndroid:
    name: buildAndroid
    runs-on: ubuntu-latest
    steps:   
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1.2.0
        with:
          haxe-version: 4.3.6

      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib git openfl https://github.com/MobilePorting/openfl 9.3.3 > /dev/null --quiet
          haxelib git flixel https://github.com/MobilePorting/flixel 5.6.1 --never --quiet
          haxelib git lime https://github.com/MobilePorting/lime f77d2c1ca97fde7dd1216232d064dd2a51f6309e
          haxelib git hxcpp https://github.com/MobilePorting/hxcpp > /dev/null
          haxelib run lime setup flixel --quiet
          haxelib install flixel-tools 1.5.1 --quiet
          haxelib install flixel-ui 2.6.3 --quiet
          haxelib install flixel-addons 3.2.3 --quiet
          haxelib install tjson --quiet
          haxelib install hxjsonast --quiet
          haxelib install hscript 2.4.0 --quiet
          haxelib install extension-androidtools
          haxelib git hxvlc https://github.com/MobilePorting/hxvlc --quiet
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc --quiet
          haxelib git linc_luajit https://github.com/MobilePorting/linc_luajit.git --quiet
          haxelib list

      - name: Setup Lime
        run: |
          haxelib run lime setup -alias -y
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_LATEST_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME_17_X64
          haxelib run lime config ANDROID_SETUP true
          haxelib set flixel-tools 1.5.1
          haxelib set flixel-ui 2.6.3
          haxelib set flixel-addons 3.2.3

      - name: Compile
        run: haxelib run lime build android -D -final -ONLY_ARM64

      - name: Publish Artifact
        uses: actions/upload-artifact@main
        with:
          name: androidBuild
          path: export/release/android/bin/app/build/outputs/apk/release/*.apk
          if-no-files-found: error
