name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  buildAndroid:
    name: buildAndroid
    runs-on: ubuntu-latest
    steps:   
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1.2.0
        with:
          haxe-version: 4.3.6

      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib git openfl https://github.com/MobilePorting/openfl 9.3.3 > /dev/null --quiet
          haxelib git flixel https://github.com/MobilePorting/flixel 5.6.1 --never --quiet
          haxelib install lime 8.2.2 > /dev/null --quiet
          haxelib git hxcpp https://github.com/MobilePorting/hxcpp > /dev/null
          haxelib run lime setup flixel --quiet
          haxelib install flixel-tools 1.5.1 --quiet
          haxelib install flixel-ui 2.6.3 --quiet
          haxelib install flixel-addons 3.2.3 --quiet
          haxelib install tjson --quiet
          haxelib install hxjsonast --quiet
          haxelib install hscript 2.4.0 --quiet
          haxelib install extension-androidtools --quiet --skip-dependencies
          haxelib git hxvlc https://github.com/MobilePorting/hxvlc --quiet --skip-dependencies
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc --quiet
          haxelib git linc_luajit https://github.com/MobilePorting/linc_luajit.git --quiet
          haxelib list

      - name: Setup Lime
        run: |
          haxelib set lime 8.2.2
          haxelib run lime setup -alias -y
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_LATEST_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME_17_X64
          haxelib run lime config ANDROID_SETUP true
          haxelib set flixel-tools 1.5.1
          haxelib set flixel-ui 2.6.3
          haxelib set flixel-addons 3.2.3

      - name: Compile Android
        run: haxelib run lime build android -final -Darch=arm64-v8a

      - name: Publish Android Artifact
        uses: actions/upload-artifact@v4
        with:
          name: androidBuild
          path: export/release/android/bin/app/build/outputs/apk/release/*.apk
          if-no-files-found: error

  buildWindows:
    name: buildWindows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1.2.0
        with:
          haxe-version: 4.3.6

      - name: Install Haxelib
        run: |
          haxelib setup C:\haxelib
          haxelib install lime 8.2.2 --quiet
          haxelib git openfl https://github.com/MobilePorting/openfl 9.3.3 --quiet
          haxelib git flixel https://github.com/MobilePorting/flixel 5.6.1 --never --quiet
          haxelib git hxcpp https://github.com/MobilePorting/hxcpp --quiet
          haxelib install hxcpp-debug-server --quiet
          haxelib run lime setup flixel
          haxelib install flixel-tools 1.5.1 --quiet
          haxelib install flixel-ui 2.6.3 --quiet
          haxelib install flixel-addons 3.2.3 --quiet
          haxelib install tjson --quiet
          haxelib install hxjsonast --quiet
          haxelib install hscript 2.4.0 --quiet
          haxelib git hxvlc https://github.com/MobilePorting/hxvlc --quiet --skip-dependencies
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc --quiet
          haxelib git linc_luajit https://github.com/MobilePorting/linc_luajit.git --quiet
          haxelib list

      - name: Setup Lime
        run: |
          haxelib set lime 8.2.2
          haxelib run lime setup -alias -y
          haxelib set flixel-tools 1.5.1
          haxelib set flixel-ui 2.6.3
          haxelib set flixel-addons 3.2.3

      - name: Compile Windows
        run: haxelib run lime build windows -final

      - name: Publish Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windowsBuild
          path: export/release/windows/bin/*
          if-no-files-found: error
