# This is a basic workflow to help you get started with Actions

name: test

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"

  buildAndroid:
    name: buildAndroid
    runs-on: ubuntu-latest
    steps:
      #- name: Increase swap memory
        #run: |
          #sudo dd if=/dev/zero of=/swapfile bs=128M count=64
          #sudo mkswap /swapfile
          #sudo swapon /swapfile
          #sudo chmod 600 /swapfile
    
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1.2.0
        with:
          haxe-version: 4.2.5

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r21e

      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install openfl 9.2.0 > /dev/null
          haxelib --never install flixel 5.2.2 --quiet
          haxelib install lime 8.0.1 > /dev/null
          haxelib git hxcpp https://github.com/mcagabe19-stuff/hxcpp.git > /dev/null
          haxelib run lime setup flixel --quiet
          haxelib install flixel-tools --quiet
          haxelib install flixel-ui --quiet
          haxelib install flixel-addons 2.12.0 --quiet
          haxelib install tjson --quiet
          haxelib install hxjsonast --quiet
          haxelib install hscript 2.4.0 --quiet
          haxelib install hxCodec 2.6.1 --quiet
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc --quiet
          haxelib git linc_luajit https://github.com/AndreiRudenko/linc_luajit --quiet
          haxelib git hscript-ex https://github.com/ianharrigan/hscript-ex --quiet
          haxelib git extension-androidtools https://github.com/Edger228/androidtools.git --skip-dependencies --quiet
          haxelib list

      - name: Setup Lime
        run: |
          haxelib run lime setup -alias -y
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_LATEST_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME_17_X64
          haxelib run lime config ANDROID_SETUP true
          haxelib set lime 8.0.1
          haxelib set openfl 9.2.0
          haxelib set hxCodec 2.6.1
          haxelib set hscript 2.4.0
          haxelib set flixel-addons 2.12.0
          haxelib set flixel 5.2.2

      - name: Compile
        run: haxelib run lime build android -final

      - name: Publish Artifact
        uses: actions/upload-artifact@main
        with:
          name: androidBuild
          path: export/release/android/bin/app/build/outputs/apk/release/*.apk
          if-no-files-found: error
