name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  buildAndroid:
    name: buildAndroid
    runs-on: ubuntu-latest
    steps:   
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Android NDK
        uses: nttld/setup-ndk@main
        id: setup-ndk
        with:
          ndk-version: r27c

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1.2.0
        with:
          haxe-version: 4.3.6

      - name: Restore Previous Cache
        id: cache-debug-build-android-restore
        uses: actions/cache/restore@main
        with:
          path: |
            ~/haxelib
            ~/.gradle
            export/release/android/haxe
            export/release/android/obj
          key: cache-android-build
          
      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          cd setup
          haxe --run HaxelibInstaller
          haxelib list

      - name: Setup Lime
        run: |
          haxelib set lime 8.1.3
          haxelib set openfl 9.2.2
          haxelib run lime setup -alias -y
          haxelib run lime config JAVA_HOME $JAVA_HOME_17_X64
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib run lime config ANDROID_SETUP true
          haxelib set flixel 5.2.2
          haxelib set flixel-tools 1.5.1
          haxelib set flixel-ui 2.6.3
          haxelib set flixel-addons 3.0.2

      - name: Compile Android
        run: haxelib run lime build android -final -ONLY_ARM64 -D LTO -D NO_CONSOLE -D HXCPP_GC_GENERATIONAL

      - name: Clear Previous Cache
        uses: actions/github-script@main
        with:
          script: |
            try {
            	const caches = await github.rest.actions.getActionsCacheList({
            		owner: context.repo.owner,
            		repo: context.repo.repo,
            	})
            	if (typeof caches.data.actions_caches != null && caches.data.actions_caches.length > 0) {
            		for (const cache of caches.data.actions_caches) {
            			if (cache.key == "cache-android-build") {
            				console.log('Clearing some ' + cache.key + '...')
            				await github.rest.actions.deleteActionsCacheById({
            					owner: context.repo.owner,
            					repo: context.repo.repo,
            					cache_id: cache.id,
            				})
            				console.log("Previous Cache Cleared!")
            			}
            		}
            	}
            } catch (error) {
            	console.log(error.message);
            }
            
      - name: Save Current Cache
        id: cache-release-build-android-save
        uses: actions/cache/save@main
        with:
          path: |
            ~/haxelib
            ~/.gradle
            export/release/android/haxe
            export/release/android/obj
          key: cache-android-build
        
      - name: Publish Android Artifact
        uses: actions/upload-artifact@v4
        with:
          name: androidBuild
          path: export/release/android/bin/app/build/outputs/apk/release/*.apk
          if-no-files-found: error

  buildWindows:
    name: buildWindows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1.2.0
        with:
          haxe-version: 4.3.6

      - name: Install Haxelib
        run: |
          haxelib setup C:\haxelib
          cd setup
          haxe --run HaxelibInstaller
          haxelib list

      - name: Setup Lime
        run: |
          haxelib set lime 8.1.3
          haxelib set openfl 9.2.2
          haxelib run lime setup -alias -y
          haxelib set flixel 5.2.2
          haxelib set flixel-tools 1.5.1
          haxelib set flixel-ui 2.6.3
          haxelib set flixel-addons 3.0.2

      - name: Compile Windows
        run: haxelib run lime build windows -D

      - name: Publish Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windowsBuild
          path: export/release/windows/bin/*
          if-no-files-found: error
