name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  buildAndroid:
    name: buildAndroid
    runs-on: ubuntu-latest
    steps:   
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1.2.0
        with:
          haxe-version: 4.3.6
          
      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install flixel 5.4.1 --never --quiet
          haxelib install format --quiet
          haxelib git hxp https://github.com/HomuHomu833-stuff/hxp.git --quiet
          haxelib git lime https://github.com/FunkinCrew/lime.git --quiet
          haxelib git openfl https://github.com/HomuHomu833-stuff/openfl.git 9.2.2 --quiet
          haxelib git hxcpp https://github.com/MobilePorting/hxcpp --quiet
          haxelib run lime setup flixel --quiet
          haxelib install flixel-tools 1.5.1 --quiet
          haxelib install flixel-ui 2.6.3 --quiet
          haxelib install flixel-addons 3.2.3 --quiet
          haxelib install box2d --quiet
          haxelib install tjson --quiet
          haxelib install hxjsonast --quiet
          haxelib install hscript --quiet
          haxelib git hxvlc https://github.com/GreenColdTea/hxvlc --quiet --skip-dependencies
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc --quiet
          haxelib git linc_luajit https://github.com/MobilePorting/linc_luajit.git --quiet
          haxelib git extension-androidtools https://github.com/MAJigsaw77/extension-androidtools.git --quiet
          haxelib list

      - name: Setup Lime
        run: |
          haxelib run lime setup -alias -y
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_LATEST_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME_17_X64
          haxelib run lime config ANDROID_SETUP true
          haxelib set flixel 5.4.1
          haxelib set flixel-tools 1.5.1
          haxelib set flixel-ui 2.6.3
          haxelib set flixel-addons 3.2.3

      - name: Compile Android
        run: haxelib run lime build android -final -ONLY_ARM64 -D LTO -D NO_CONSOLE -D HXCPP_GC_GENERATIONAL

      - name: Clear Previous Cache
        uses: actions/github-script@main
        with:
          script: |
            try {
            	const caches = await github.rest.actions.getActionsCacheList({
            		owner: context.repo.owner,
            		repo: context.repo.repo,
            	})
            	if (typeof caches.data.actions_caches != null && caches.data.actions_caches.length > 0) {
            		for (const cache of caches.data.actions_caches) {
            			if (cache.key == "cache-android-build") {
            				console.log('Clearing some ' + cache.key + '...')
            				await github.rest.actions.deleteActionsCacheById({
            					owner: context.repo.owner,
            					repo: context.repo.repo,
            					cache_id: cache.id,
            				})
            				console.log("Previous Cache Cleared!")
            			}
            		}
            	}
            } catch (error) {
            	console.log(error.message);
            }
            
      - name: Save Current Cache
        id: cache-release-build-android-save
        uses: actions/cache/save@main
        with:
          path: |
            ~/haxelib
            ~/.gradle
            export/release/android/haxe
            export/release/android/obj
          key: cache-android-build
        
      - name: Publish Android Artifact
        uses: actions/upload-artifact@v4
        with:
          name: androidBuild
          path: export/release/android/bin/app/build/outputs/apk/release/*.apk
          if-no-files-found: error

  buildWindows:
    name: buildWindows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1.2.0
        with:
          haxe-version: 4.3.6

      - name: Install Haxelib
        run: |
          haxelib setup C:\haxelib
          haxelib install flixel 5.4.1 --quiet --never
          haxelib install lime 8.1.3 --quiet
          haxelib git openfl https://github.com/HomuHomu833-stuff/openfl.git 9.2.2 --quiet
          haxelib install hxcpp --quiet
          haxelib install hxcpp-debug-server --quiet
          haxelib run lime setup flixel
          haxelib install flixel-tools 1.5.1 --quiet
          haxelib install flixel-ui 2.6.3 --quiet
          haxelib install flixel-addons 3.2.3 --quiet
          haxelib install box2d --quiet
          haxelib install tjson --quiet
          haxelib install hxjsonast --quiet
          haxelib install hscript --quiet
          haxelib git hxvlc https://github.com/GreenColdTea/hxvlc --quiet --skip-dependencies
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc --quiet
          haxelib git linc_luajit https://github.com/MobilePorting/linc_luajit.git --quiet
          haxelib list

      - name: Setup Lime
        run: |
          haxelib set lime 8.1.3
          haxelib run lime setup -alias -y
          haxelib set flixel 5.4.1
          haxelib set flixel-tools 1.5.1
          haxelib set flixel-ui 2.6.3
          haxelib set flixel-addons 3.2.3

      - name: Compile Windows
        run: haxelib run lime build windows -D

      - name: Publish Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windowsBuild
          path: export/release/windows/bin/*
          if-no-files-found: error
